source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
project 'CurrencyConverter'
inhibit_all_warnings!
use_frameworks!

def shared_pods 
    pod 'ReactiveCocoa'
    pod 'Swinject'
    pod 'RealmSwift'
end

target "CurrencyConverter" do 
    shared_pods
end

target "CurrencyConverterTests" do
    shared_pods
end
